name: CI/CD - Build, Test & Publish Docker Image

# workflow przy każdym wypchnięciu zmian na main
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    
    steps:
      # pobranie kodu z repozytorium
      - name: Checkout code
        uses: actions/checkout@v4

      # konfiguracja Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # build i test
      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true # wysyła obraz do Docker Hub
          # tworzy nazwę obrazu
          tags: ${{ secrets.DOCKER_USERNAME }}/nowatorski_projekt_ind:latest

      # informacja końcowa
      - name: Success Message
        run: echo "Obraz został zbudowany i wysłany na Docker Hub!"