name: CI/CD - Integration Tests with Compose

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-and-publish:
    runs-on: ubuntu-latest

    steps:
      # pobranie kodu
      - name: Checkout code
        uses: actions/checkout@v4

      # logowanie do Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # uruchomienie środowiska testowego
      - name: Start services with Docker Compose
        run: |
          docker compose up -d --build
          echo "Czekam 10 sekund na start bazy danych..."
          sleep 10  # Proste oczekiwanie na gotowość Postgresa

      # testy wewnątrz kontenera -T wyłącza interaktywny terminal
      - name: Run Tests inside Docker
        run: docker compose exec -T web pytest

      # zatrzymanie kontenerów
      - name: Tear down Docker Compose
        run: docker compose down

      # 6. budowanie i publikacja finalnego obrazu jeśli testy przeszły
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/nowatorski_projekt_ind:latest