name: CI/CD - Integration Tests & Publish

# kiedy uruchamiać pipeline
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-and-publish:
    runs-on: ubuntu-latest

    steps:
      # pobranie kodu z repozytorium
      - name: Checkout code
        uses: actions/checkout@v4

      # logowanie do Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # uruchomienie środowiska testowego Docker Compose
      - name: Start services with Docker Compose
        run: |
          docker compose up -d --build
          
          echo "Czekam 15 sekund na pełny start aplikacji i bazy danych..."
          sleep 15
          
          echo "Sprawdzam stan kontenerów:"
          docker compose ps -a
          
          echo "Wyświetlam ostatnie logi aplikacji (dla debugowania):"
          docker compose logs web
          # ------------------------------------------------------

      # uruchomienie testów wewnątrz działającego kontenera -T wyłącza interaktywność
      - name: Run Tests inside Docker
        run: docker compose exec -T web pytest

      # zatrzymanie i usunięcie kontenerów
      - name: Tear down Docker Compose
        run: docker compose down

      # konfiguracja narzędzia Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Budowanie i Publikacja
      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          # Pushuj tylko, jeśli to nie jest Pull Request
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ secrets.DOCKER_USERNAME }}/nowatorski_projekt_ind:latest